import { describe, expect, it } from 'vitest'
import { generateCode } from '../src/code-generator.js'
import type { TransformedSchema } from '../src/types.js'

function makeSchema(partial: Partial<TransformedSchema>): TransformedSchema {
  return { models: [], ...partial }
}

describe('generateCode', () => {
  describe('file header and imports', () => {
    it('includes a do-not-edit comment header', () => {
      const schema = makeSchema({ models: [] })
      const code = generateCode(schema)
      expect(code).toContain('Do NOT edit this file manually')
    })

    it('always imports table, createSchema and createBuilder', () => {
      const schema = makeSchema({ models: [] })
      const code = generateCode(schema)
      expect(code).toContain('createBuilder')
      expect(code).toContain('createSchema')
      expect(code).toContain('table')
    })

    it('imports string when a string() column is present', () => {
      const schema = makeSchema({
        models: [
          {
            modelName: 'User',
            tableName: 'User',
            originalTableName: null,
            zeroTableName: 'userTable',
            primaryKey: ['id'],
            columns: { id: { type: 'string()', isOptional: false, mappedName: null } },
            relationships: {},
          },
        ],
      })
      expect(generateCode(schema)).toContain('string')
    })

    it('imports relationships when at least one relation exists', () => {
      const schema = makeSchema({
        models: [
          {
            modelName: 'Post',
            tableName: 'Post',
            originalTableName: null,
            zeroTableName: 'postTable',
            primaryKey: ['id'],
            columns: { id: { type: 'string()', isOptional: false, mappedName: null } },
            relationships: {
              author: { type: 'one', sourceField: ['authorId'], destField: ['id'], destSchema: 'userTable' },
            },
          },
        ],
      })
      expect(generateCode(schema)).toContain('relationships')
    })
  })

  describe('table definitions', () => {
    it('generates a table constant with correct name', () => {
      const schema = makeSchema({
        models: [
          {
            modelName: 'Room',
            tableName: 'Room',
            originalTableName: null,
            zeroTableName: 'roomTable',
            primaryKey: ['id'],
            columns: { id: { type: 'string()', isOptional: false, mappedName: null } },
            relationships: {},
          },
        ],
      })
      expect(generateCode(schema)).toContain('export const roomTable = table("Room")')
    })

    it('adds .from() when originalTableName differs from tableName', () => {
      const schema = makeSchema({
        models: [
          {
            modelName: 'User',
            tableName: 'User',
            originalTableName: 'users',
            zeroTableName: 'userTable',
            primaryKey: ['id'],
            columns: { id: { type: 'string()', isOptional: false, mappedName: null } },
            relationships: {},
          },
        ],
      })
      expect(generateCode(schema)).toContain('.from("users")')
    })

    it('appends .optional() for nullable columns', () => {
      const schema = makeSchema({
        models: [
          {
            modelName: 'User',
            tableName: 'User',
            originalTableName: null,
            zeroTableName: 'userTable',
            primaryKey: ['id'],
            columns: {
              id: { type: 'string()', isOptional: false, mappedName: null },
              bio: { type: 'string()', isOptional: true, mappedName: null },
            },
            relationships: {},
          },
        ],
      })
      const code = generateCode(schema)
      expect(code).toContain('bio: string().optional()')
    })

    it('adds .from() on the column when mappedName is set', () => {
      const schema = makeSchema({
        models: [
          {
            modelName: 'User',
            tableName: 'User',
            originalTableName: null,
            zeroTableName: 'userTable',
            primaryKey: ['id'],
            columns: {
              id: { type: 'string()', isOptional: false, mappedName: null },
              createdAt: { type: 'number()', isOptional: false, mappedName: 'created_at' },
            },
            relationships: {},
          },
        ],
      })
      const code = generateCode(schema)
      expect(code).toContain("createdAt: number().from('created_at')")
    })

    it('emits .primaryKey() with the correct field name', () => {
      const schema = makeSchema({
        models: [
          {
            modelName: 'User',
            tableName: 'User',
            originalTableName: null,
            zeroTableName: 'userTable',
            primaryKey: ['id'],
            columns: { id: { type: 'string()', isOptional: false, mappedName: null } },
            relationships: {},
          },
        ],
      })
      expect(generateCode(schema)).toContain('.primaryKey("id")')
    })
  })

  describe('relationships definitions', () => {
    it('does not emit a relationships constant when model has no relations', () => {
      const schema = makeSchema({
        models: [
          {
            modelName: 'User',
            tableName: 'User',
            originalTableName: null,
            zeroTableName: 'userTable',
            primaryKey: ['id'],
            columns: { id: { type: 'string()', isOptional: false, mappedName: null } },
            relationships: {},
          },
        ],
      })
      expect(generateCode(schema)).not.toContain('userTableRelationships')
    })

    it('emits a relationships constant for one-link relations', () => {
      const schema = makeSchema({
        models: [
          {
            modelName: 'Post',
            tableName: 'Post',
            originalTableName: null,
            zeroTableName: 'postTable',
            primaryKey: ['id'],
            columns: { id: { type: 'string()', isOptional: false, mappedName: null } },
            relationships: {
              author: { type: 'one', sourceField: ['authorId'], destField: ['id'], destSchema: 'userTable' },
            },
          },
        ],
      })
      const code = generateCode(schema)
      expect(code).toContain('postTableRelationships')
      expect(code).toContain('one(')
      expect(code).toContain('"authorId"')
      expect(code).toContain('destSchema: userTable')
    })

    it('emits many() with chain for manyToMany relations', () => {
      const schema = makeSchema({
        models: [
          {
            modelName: 'Post',
            tableName: 'Post',
            originalTableName: null,
            zeroTableName: 'postTable',
            primaryKey: ['id'],
            columns: { id: { type: 'string()', isOptional: false, mappedName: null } },
            relationships: {
              tags: {
                type: 'many',
                chain: [
                  { sourceField: ['id'], destField: ['post_id'], destSchema: 'postTagsTable' },
                  { sourceField: ['tag_id'], destField: ['id'], destSchema: 'tagTable' },
                ],
              },
            },
          },
        ],
      })
      const code = generateCode(schema)
      expect(code).toContain('many(')
      expect(code).toContain('postTagsTable')
      expect(code).toContain('tagTable')
    })
  })

  describe('createSchema export', () => {
    it('includes tables array in createSchema', () => {
      const schema = makeSchema({
        models: [
          {
            modelName: 'User',
            tableName: 'User',
            originalTableName: null,
            zeroTableName: 'userTable',
            primaryKey: ['id'],
            columns: { id: { type: 'string()', isOptional: false, mappedName: null } },
            relationships: {},
          },
        ],
      })
      const code = generateCode(schema)
      expect(code).toContain('tables: [')
      expect(code).toContain('userTable,')
    })

    it('omits relationships array when no relations exist', () => {
      const schema = makeSchema({
        models: [
          {
            modelName: 'User',
            tableName: 'User',
            originalTableName: null,
            zeroTableName: 'userTable',
            primaryKey: ['id'],
            columns: { id: { type: 'string()', isOptional: false, mappedName: null } },
            relationships: {},
          },
        ],
      })
      expect(generateCode(schema)).not.toContain('relationships: [')
    })

    it('includes relationships array when a relation exists', () => {
      const schema = makeSchema({
        models: [
          {
            modelName: 'Post',
            tableName: 'Post',
            originalTableName: null,
            zeroTableName: 'postTable',
            primaryKey: ['id'],
            columns: { id: { type: 'string()', isOptional: false, mappedName: null } },
            relationships: {
              author: { type: 'one', sourceField: ['authorId'], destField: ['id'], destSchema: 'userTable' },
            },
          },
        ],
      })
      const code = generateCode(schema)
      expect(code).toContain('relationships: [')
      expect(code).toContain('postTableRelationships,')
    })

    it('exports Schema type and zql builder', () => {
      const schema = makeSchema({ models: [] })
      const code = generateCode(schema)
      expect(code).toContain('export type Schema = typeof schema')
      expect(code).toContain('export const zql = createBuilder(schema)')
    })
  })
})
