import { describe, expect, it } from 'vitest'
import CodeGenerator from '../src/code-generator.js'
import { Config } from '../src/config.js'
import type { TransformedSchema } from '../src/schema-transformer.js'

function generateCode(schema: TransformedSchema, camelCase = false): string {
  const config = new Config({ modelsSourcePath: '.', camelCase }, process.cwd(), 'tsconfig.json')
  const gen = new CodeGenerator(config, schema)
  return (gen as any).generate()
}

function makeSchema(partial: Partial<TransformedSchema>): TransformedSchema {
  return { models: [], ...partial }
}

describe('generateCode', () => {
  describe('file header and imports', () => {
    it('includes a do-not-edit comment header', () => {
      const code = generateCode(makeSchema({ models: [] }))
      expect(code).toContain('Do NOT edit this file manually')
    })

    it('always imports table, createSchema and createBuilder', () => {
      const code = generateCode(makeSchema({ models: [] }))
      expect(code).toContain('createBuilder')
      expect(code).toContain('createSchema')
      expect(code).toContain('table')
    })

    it('imports string when a string() column is present', () => {
      const schema = makeSchema({
        models: [
          {
            tableName: 'users',
            primaryKey: ['id'],
            columns: { id: { type: 'string()', isOptional: false } },
            relationships: {},
          },
        ],
      })
      expect(generateCode(schema)).toContain('string')
    })

    it('imports relationships when at least one relation exists', () => {
      const schema = makeSchema({
        models: [
          {
            tableName: 'posts',
            primaryKey: ['id'],
            columns: { id: { type: 'string()', isOptional: false } },
            relationships: {
              author: {
                type: 'one',
                sourceField: ['author_id'],
                destinationField: ['id'],
                destinationTable: 'users',
              },
            },
          },
        ],
      })
      expect(generateCode(schema)).toContain('relationships')
    })
  })

  describe('table definitions', () => {
    it('generates a table constant with correct name', () => {
      const schema = makeSchema({
        models: [
          {
            tableName: 'room',
            primaryKey: ['id'],
            columns: { id: { type: 'string()', isOptional: false } },
            relationships: {},
          },
        ],
      })
      expect(generateCode(schema)).toContain('export const room = table("room")')
    })

    it('adds .from() on the table when camelCase converts the table name', () => {
      const schema = makeSchema({
        models: [
          {
            tableName: 'user_accounts',
            primaryKey: ['id'],
            columns: { id: { type: 'string()', isOptional: false } },
            relationships: {},
          },
        ],
      })
      const code = generateCode(schema, true)
      expect(code).toContain('export const userAccounts = table("userAccounts")')
      expect(code).toContain('.from("user_accounts")')
    })

    it('appends .optional() for nullable columns', () => {
      const schema = makeSchema({
        models: [
          {
            tableName: 'users',
            primaryKey: ['id'],
            columns: {
              id: { type: 'string()', isOptional: false },
              bio: { type: 'string()', isOptional: true },
            },
            relationships: {},
          },
        ],
      })
      expect(generateCode(schema)).toContain('bio: string().optional()')
    })

    it('adds .from() on the column when camelCase converts the column name', () => {
      const schema = makeSchema({
        models: [
          {
            tableName: 'users',
            primaryKey: ['id'],
            columns: {
              id: { type: 'string()', isOptional: false },
              created_at: { type: 'number()', isOptional: false },
            },
            relationships: {},
          },
        ],
      })
      expect(generateCode(schema, true)).toContain("createdAt: number().from('created_at')")
    })

    it('emits .primaryKey() with the correct field name', () => {
      const schema = makeSchema({
        models: [
          {
            tableName: 'users',
            primaryKey: ['id'],
            columns: { id: { type: 'string()', isOptional: false } },
            relationships: {},
          },
        ],
      })
      expect(generateCode(schema)).toContain('.primaryKey("id")')
    })
  })

  describe('relationships definitions', () => {
    it('does not emit a relationships constant when model has no relations', () => {
      const schema = makeSchema({
        models: [
          {
            tableName: 'users',
            primaryKey: ['id'],
            columns: { id: { type: 'string()', isOptional: false } },
            relationships: {},
          },
        ],
      })
      expect(generateCode(schema)).not.toContain('users_relationships')
    })

    it('emits a relationships constant for one-link relations', () => {
      const schema = makeSchema({
        models: [
          {
            tableName: 'posts',
            primaryKey: ['id'],
            columns: { id: { type: 'string()', isOptional: false } },
            relationships: {
              author: {
                type: 'one',
                sourceField: ['author_id'],
                destinationField: ['id'],
                destinationTable: 'users',
              },
            },
          },
        ],
      })
      const code = generateCode(schema)
      expect(code).toContain('posts_relationships')
      expect(code).toContain('one(')
      expect(code).toContain('"author_id"')
      expect(code).toContain('destSchema: users')
    })

    it('emits many() with chain for manyToMany relations', () => {
      const schema = makeSchema({
        models: [
          {
            tableName: 'posts',
            primaryKey: ['id'],
            columns: { id: { type: 'string()', isOptional: false } },
            relationships: {
              tags: {
                type: 'many',
                chain: [
                  {
                    sourceField: ['id'],
                    destinationField: ['post_id'],
                    destinationTable: 'post_tags',
                  },
                  {
                    sourceField: ['tag_id'],
                    destinationField: ['id'],
                    destinationTable: 'tags',
                  },
                ],
              },
            },
          },
        ],
      })
      const code = generateCode(schema)
      expect(code).toContain('many(')
      expect(code).toContain('post_tags')
      expect(code).toContain('tags')
    })
  })

  describe('createSchema export', () => {
    it('includes tables array in createSchema', () => {
      const schema = makeSchema({
        models: [
          {
            tableName: 'users',
            primaryKey: ['id'],
            columns: { id: { type: 'string()', isOptional: false } },
            relationships: {},
          },
        ],
      })
      const code = generateCode(schema)
      expect(code).toContain('tables: [')
      expect(code).toContain('users,')
    })

    it('omits relationships array when no relations exist', () => {
      const schema = makeSchema({
        models: [
          {
            tableName: 'users',
            primaryKey: ['id'],
            columns: { id: { type: 'string()', isOptional: false } },
            relationships: {},
          },
        ],
      })
      expect(generateCode(schema)).not.toContain('relationships: [')
    })

    it('includes relationships array when a relation exists', () => {
      const schema = makeSchema({
        models: [
          {
            tableName: 'posts',
            primaryKey: ['id'],
            columns: { id: { type: 'string()', isOptional: false } },
            relationships: {
              author: {
                type: 'one',
                sourceField: ['author_id'],
                destinationField: ['id'],
                destinationTable: 'users',
              },
            },
          },
        ],
      })
      const code = generateCode(schema)
      expect(code).toContain('relationships: [')
      expect(code).toContain('posts_relationships,')
    })

    it('exports Schema type and zql builder', () => {
      const code = generateCode(makeSchema({ models: [] }))
      expect(code).toContain('export type Schema = typeof schema')
      expect(code).toContain('export const zql = createBuilder(schema)')
    })
  })
})
