import type { TransformedSchema, ZeroModel, ZeroRelationship, ZeroTypeMapping } from './types.js'
import { toZeroRelationshipsName } from './schema-mapper.js'

const HEADER = `// This file was automatically generated by lucid-zero.
// Do NOT edit this file manually — it will be overwritten on the next run.`

// ----------------------------------------------------------------
// Imports
// ----------------------------------------------------------------

function generateImports(schema: TransformedSchema): string {
  const used = new Set<string>(['table', 'createSchema', 'createBuilder'])

  for (const model of schema.models) {
    for (const col of Object.values(model.columns)) {
      const base = col.type.match(/^([a-z]+)/)?.[1]
      if (base) used.add(base)
    }
    if (Object.keys(model.relationships).length > 0) {
      used.add('relationships')
    }
  }

  const sorted = [...used].sort()
  return `import {\n  ${sorted.join(',\n  ')},\n} from "@rocicorp/zero";\n\n`
}

// ----------------------------------------------------------------
// Table definitions
// ----------------------------------------------------------------

function generateColumnDef(name: string, col: ZeroTypeMapping): string {
  let expr = col.type

  if (col.mappedName) {
    expr += `.from('${col.mappedName}')`
  }
  if (col.isOptional) {
    expr += `.optional()`
  }

  return `    ${name}: ${expr}`
}

function generateTableDef(model: ZeroModel): string {
  let out = `export const ${model.zeroTableName} = table("${model.tableName}")`

  if (model.originalTableName) {
    out += `\n  .from("${model.originalTableName}")`
  }

  out += '\n  .columns({\n'

  for (const [name, col] of Object.entries(model.columns)) {
    out += generateColumnDef(name, col) + ',\n'
  }

  out += '  })'
  out += `\n  .primaryKey(${model.primaryKey.map((k) => `"${k}"`).join(', ')});\n`

  return out
}

// ----------------------------------------------------------------
// Relationships
// ----------------------------------------------------------------

function generateRelationshipConfig(rel: ZeroRelationship): string {
  if ('chain' in rel) {
    return rel.chain
      .map(
        (link) =>
          `{\n      sourceField: ${JSON.stringify(link.sourceField)},\n      destField: ${JSON.stringify(link.destField)},\n      destSchema: ${link.destSchema},\n    }`,
      )
      .join(', ')
  }

  return `{\n    sourceField: ${JSON.stringify(rel.sourceField)},\n    destField: ${JSON.stringify(rel.destField)},\n    destSchema: ${rel.destSchema},\n  }`
}

function generateRelationshipsDef(model: ZeroModel): string {
  const entries = Object.entries(model.relationships)
  if (entries.length === 0) return ''

  const hasOne = entries.some(([, r]) => r.type === 'one')
  const hasMany = entries.some(([, r]) => r.type === 'many')
  const imports = [hasOne && 'one', hasMany && 'many'].filter(Boolean).join(', ')

  const rels = entries
    .map(([name, rel]) => `  ${name}: ${rel.type}(${generateRelationshipConfig(rel)})`)
    .join(',\n')

  return (
    `export const ${toZeroRelationshipsName(model.modelName)} = ` +
    `relationships(${model.zeroTableName}, ({ ${imports} }) => ({\n${rels}\n}));\n`
  )
}

// ----------------------------------------------------------------
// Schema export
// ----------------------------------------------------------------

function generateSchema(schema: TransformedSchema): string {
  const hasRelationships = schema.models.some(
    (m) => Object.keys(m.relationships).length > 0,
  )

  let out = `\nexport const schema = createSchema({\n`
  out += `  tables: [\n`
  for (const model of schema.models) {
    out += `    ${model.zeroTableName},\n`
  }
  out += `  ],\n`

  if (hasRelationships) {
    out += `  relationships: [\n`
    for (const model of schema.models) {
      if (Object.keys(model.relationships).length > 0) {
        out += `    ${toZeroRelationshipsName(model.modelName)},\n`
      }
    }
    out += `  ],\n`
  }

  out += `});\n\n`
  out += `export type Schema = typeof schema;\n`
  out += `\nexport const zql = createBuilder(schema);\n`

  return out
}

// ----------------------------------------------------------------
// Entry point
// ----------------------------------------------------------------

export function generateCode(schema: TransformedSchema): string {
  let out = HEADER + '\n\n'
  out += generateImports(schema)

  for (const model of schema.models) {
    out += generateTableDef(model) + '\n'
  }

  for (const model of schema.models) {
    const rel = generateRelationshipsDef(model)
    if (rel) out += rel + '\n'
  }

  out += generateSchema(schema)

  return out
}
