import type { Config } from './config.js'
import fs from 'node:fs'
import { Formatter } from './formatter.js'
import type { TransformedSchema, ZeroModel, ZeroRelationshipProperties, ZeroColumnProperties } from './schema-transformer.js'
import { toCamelCase } from './utils.js'

const HEADER = `// This file was automatically generated by lucid-zero.
// Do NOT edit this file manually — it will be overwritten on the next run.`

export default class CodeGenerator {
  private config: Config
  private schema: TransformedSchema

  constructor(config: Config, schema: TransformedSchema) {
    this.config = config
    this.schema = schema
  }

  async generateToOutputFile() {
    let code = this.generate()

    if (this.config.formatOutputFile) {
      code = await Formatter.format(code)
    }

    fs.writeFileSync(this.config.outputFilePath, code)
  }

  private generate(): string {
    let out = HEADER + '\n\n'
    out += this.generateImports()

    for (const model of this.schema.models) {
      out += this.generateTableDefinitions(model) + '\n'
    }

    for (const model of this.schema.models) {
      const rel = this.generateRelationshipsDefinitions(model)
      if (rel) out += rel + '\n'
    }

    out += this.generateExports()

    return out
  }

  private generateImports(): string {
    const used = new Set<string>(['table', 'createSchema', 'createBuilder'])

    for (const model of this.schema.models) {
      for (const col of Object.values(model.columns)) {
        const baseTypeName = col.type.match(/^([a-z]+)/)?.[1]
        if (baseTypeName) used.add(baseTypeName)
      }
      if (Object.keys(model.relationships).length > 0) {
        used.add('relationships')
      }
    }

    const sorted = [...used].sort()
    return `import {\n  ${sorted.join(',\n  ')},\n} from "@rocicorp/zero";\n\n`
  }

  private generateColumnDefinitions(dbColName: string, col: ZeroColumnProperties): string {
    const zeroColName = this.toZeroName(dbColName)
    let expr = col.type

    if (zeroColName !== dbColName) {
      expr += `.from('${dbColName}')`
    }

    if (col.isOptional) {
      expr += `.optional()`
    }

    return `    ${zeroColName}: ${expr}`
  }

  private toZeroName(name: string): string {
    return toCamelCase(name)
  }

  private relationshipVariableName(model: ZeroModel): string {
    return toCamelCase(model.tableName) + 'Relationships'
  }

  private generateTableDefinitions(model: ZeroModel): string {
    const zeroName = this.toZeroName(model.tableName)
    let out = `export const ${zeroName} = table("${zeroName}")`

    if (zeroName !== model.tableName) {
      out += `\n  .from("${model.tableName}")`
    }

    out += '\n  .columns({\n'

    for (const [dbColName, col] of Object.entries(model.columns)) {
      out += this.generateColumnDefinitions(dbColName, col) + ',\n'
    }

    out += '  })'
    out += `\n  .primaryKey(${model.primaryKey.map((k) => `"${this.toZeroName(k)}"`).join(', ')});\n`

    return out
  }

  private generateRelationshipsDefinitions(model: ZeroModel): string {
    const relationEntries = Object.entries(model.relationships)
    if (relationEntries.length === 0) return ''

    const hasOne = relationEntries.some(([, rel]) => rel.type === 'one')
    const hasMany = relationEntries.some(([, rel]) => rel.type === 'many')
    const destructured = [hasOne && 'one', hasMany && 'many'].filter(Boolean).join(', ')

    const zeroName = this.toZeroName(model.tableName)
    const body = relationEntries
      .map(([name, rel]) => `  ${this.toZeroName(name)}: ${rel.type}(${this.generateRelationshipConfig(rel)})`)
      .join(',\n')

    return (
      `export const ${this.relationshipVariableName(model)} = ` +
      `relationships(${zeroName}, ({ ${destructured} }) => ({\n${body}\n}));\n`
    )
  }

  private zeroFields(fields: string[]): string {
    return JSON.stringify(fields.map((f) => this.toZeroName(f)))
  }

  private generateRelationshipConfig(rel: ZeroRelationshipProperties): string {
    if ('chain' in rel) {
      return rel.chain
        .map((link) => [
          `{`,
          `      sourceField: ${this.zeroFields(link.sourceField)},`,
          `      destField: ${this.zeroFields(link.destinationField)},`,
          `      destSchema: ${this.toZeroName(link.destinationTable)},`,
          `    }`,
        ].join('\n'))
        .join(', ')
    }

    return [
      `{`,
      `    sourceField: ${this.zeroFields(rel.sourceField)},`,
      `    destField: ${this.zeroFields(rel.destinationField)},`,
      `    destSchema: ${this.toZeroName(rel.destinationTable)},`,
      `  }`,
    ].join('\n')
  }

  private generateExports(): string {
    const hasRelationships = this.schema.models.some(
      (model) => Object.keys(model.relationships).length > 0,
    )

    let out = `\nexport const schema = createSchema({\n`
    out += `  tables: [\n`
    for (const model of this.schema.models) {
      out += `    ${this.toZeroName(model.tableName)},\n`
    }
    out += `  ],\n`

    if (hasRelationships) {
      out += `  relationships: [\n`
      for (const model of this.schema.models) {
        if (Object.keys(model.relationships).length > 0) {
          out += `    ${this.relationshipVariableName(model)},\n`
        }
      }
      out += `  ],\n`
    }

    out += `});\n\n`
    out += `export type Schema = typeof schema;\n`
    out += `\nexport const zql = createBuilder(schema);\n`

    return out
  }
}
