import type { ResolvedConfig } from './config.js'
import fs from 'node:fs'
import { Formatter } from './formatter.js'
import type { TransformedSchema, ZeroModel, ZeroRelationshipProperties, ZeroColumnProperties } from './schema-transformer.js'
import { toCamelCase } from './utils.js'

const HEADER = `// This file was automatically generated by lucid-zero.
// Do NOT edit this file manually — it will be overwritten on the next run.`

export default class CodeGenerator {
  private config: ResolvedConfig
  private schema: TransformedSchema

  constructor(config: ResolvedConfig, schema: TransformedSchema) {
    this.config = config
    this.schema = schema
  }

  async generateToOutputFile() {
    let code = this.generate()

    if (this.config.formatOutputFile) {
      code = await Formatter.format(code)
    }

    fs.writeFileSync(this.config.outputFilePath, code)
  }

  private generate(): string {
    let out = HEADER + '\n\n'
    out += this.generateImports()

    for (const model of this.schema.models) {
      out += this.generateTableDefinitions(model) + '\n'
    }

    for (const model of this.schema.models) {
      const rel = this.generateRelationshipsDefinitions(model)
      if (rel) out += rel + '\n'
    }

    out += this.generateExports()

    return out
  }

  private generateImports(): string {
    const used = new Set<string>(['table', 'createSchema', 'createBuilder'])

    for (const model of this.schema.models) {
      for (const col of Object.values(model.columns)) {
        const base = col.type.match(/^([a-z]+)/)?.[1]
        if (base) used.add(base)
      }
      if (Object.keys(model.relationships).length > 0) {
        used.add('relationships')
      }
    }

    const sorted = [...used].sort()
    return `import {\n  ${sorted.join(',\n  ')},\n} from "@rocicorp/zero";\n\n`
  }

  private generateColumnDefinitions(dbColName: string, col: ZeroColumnProperties): string {
    const zeroColName = this.toZeroName(dbColName)
    let expr = col.type

    if (zeroColName !== dbColName) {
      expr += `.from('${dbColName}')`
    }

    if (col.isOptional) {
      expr += `.optional()`
    }

    return `    ${zeroColName}: ${expr}`
  }

  private toZeroName(name: string): string {
    return this.config.camelCase ? toCamelCase(name) : name
  }

  private tableVar(model: ZeroModel): string {
    return this.toZeroName(model.tableName) + 'Table'
  }

  private relationshipsVar(model: ZeroModel): string {
    return this.toZeroName(model.tableName) + 'Relationships'
  }

  private generateTableDefinitions(model: ZeroModel): string {
    const zeroName = this.toZeroName(model.tableName)
    let out = `export const ${this.tableVar(model)} = table("${zeroName}")`

    if (zeroName !== model.tableName) {
      out += `\n  .from("${model.tableName}")`
    }

    out += '\n  .columns({\n'

    for (const [dbColName, col] of Object.entries(model.columns)) {
      out += this.generateColumnDefinitions(dbColName, col) + ',\n'
    }

    out += '  })'
    out += `\n  .primaryKey(${model.primaryKey.map((k) => `"${this.toZeroName(k)}"`).join(', ')});\n`

    return out
  }

  private generateRelationshipsDefinitions(model: ZeroModel): string {
    const entries = Object.entries(model.relationships)
    if (entries.length === 0) return ''

    const hasOne = entries.some(([, r]) => r.type === 'one')
    const hasMany = entries.some(([, r]) => r.type === 'many')
    const imports = [hasOne && 'one', hasMany && 'many'].filter(Boolean).join(', ')

    const rels = entries
      .map(([name, rel]) => `  ${name}: ${rel.type}(${this.generateRelationshipConfig(rel)})`)
      .join(',\n')

    return (
      `export const ${this.relationshipsVar(model)} = ` +
      `relationships(${this.tableVar(model)}, ({ ${imports} }) => ({\n${rels}\n}));\n`
    )
  }

  private generateRelationshipConfig(rel: ZeroRelationshipProperties): string {
    if ('chain' in rel) {
      return rel.chain
        .map(
          (link) =>
            `{\n      sourceField: ${JSON.stringify(link.sourceField)},\n      destField: ${JSON.stringify(link.destinationField)},\n      destSchema: ${this.toZeroName(link.destinationTable)}Table,\n    }`,
        )
        .join(', ')
    }

    return `{\n    sourceField: ${JSON.stringify(rel.sourceField)},\n    destField: ${JSON.stringify(rel.destinationField)},\n    destSchema: ${this.toZeroName(rel.destinationTable)}Table,\n  }`
  }

  private generateExports(): string {
    const hasRelationships = this.schema.models.some(
      (m) => Object.keys(m.relationships).length > 0,
    )

    let out = `\nexport const schema = createSchema({\n`
    out += `  tables: [\n`
    for (const model of this.schema.models) {
      out += `    ${this.tableVar(model)},\n`
    }
    out += `  ],\n`

    if (hasRelationships) {
      out += `  relationships: [\n`
      for (const model of this.schema.models) {
        if (Object.keys(model.relationships).length > 0) {
          out += `    ${this.relationshipsVar(model)},\n`
        }
      }
      out += `  ],\n`
    }

    out += `});\n\n`
    out += `export type Schema = typeof schema;\n`
    out += `\nexport const zql = createBuilder(schema);\n`

    return out
  }
}
